# Generated by Django 3.0 on 2020-10-18 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMDBCHECK', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name': '服务器管理', 'verbose_name_plural': '服务器管理'},
        ),
        migrations.AlterModelTable(
            name='server',
            table='servers',
        ),
    ]
